### PR TITLE
Arley's GSoC pull request.

### PR DESCRIPTION
**Pull request by arleyristar**
In this pull request i leaved all the commits from arleyristar fork, but the head is reverted to the 5106eeb commmit with the addiction of commit 872f35b less the optimization/pstest folder that was there just for test.
I tested the building and the tests, and it was ok.

### CODE REVIEW

**Comment by ngeiswei** [comment]
Compiling test (make -j4 test) shows that:
```
[ 84%] [ 84%] Building CXX object tests/moses/CMakeFiles/representationUTest.dir/representationUTest.cpp.o
Building CXX object tests/moses/CMakeFiles/FieldSetUTest.dir/FieldSetUTest.cpp.o
In file included from /home/nilg/OpenCog/moses-arleyristar/build/tests/moses/FieldSetUTest.cpp:24:0:
/home/nilg/OpenCog/moses-arleyristar/tests/moses/FieldSetUTest.cxxtest: In member function ‘void FieldSetUTest::test_set_get_contin()’:
/home/nilg/OpenCog/moses-arleyristar/tests/moses/FieldSetUTest.cxxtest:15:58: error: no matching function for call to ‘opencog::moses::field_set::contin_spec::contin_spec(double, double, double, int)’
         field_set fs(field_set::contin_spec(0.0,0.5,0.5,4), 1);
```

**Comment by arleyristar** [comment]
I'll see that in some hours.

**Comment by arleyristar** [comment]
I'm sorry, i forgot to fetch the upstream and merge with my code before
made the pull request (probably because it hadn't any merge problem).
But after i did that here and i ran the tests (make -j4 test), i don't see
this error.
This error should just happen if i had leaved the change in the
representation, which was not the case, i even created a branch in my
project just for it.
i fixed the pull request and it passes the cicleci test now.

**Comment by ngeiswei** [comment]
Hi @arleyristar I don't understand what this giant commit does https://github.com/arleyristar/moses/commit/338e7a3b2457fbb765a6da33638e5e03ddf79276 the commit message doesn't explain anything, that makes it rather hard to review. Besides it contains at multiple places extra whitespace, like
```
 /**
  * determine the initial exemplar given its output type
  */
 combo_tree type_to_exemplar(type_node type);
-
+        
```
that makes it look a bit fishy.

**Comment by ngeiswei** [comment]
I'm really lost, all the things I've mentioned in my previous message are absent from the "Files changed" tab of the pull request. Is github playing tricks on us? Any idea what's going anyone?

@arleyristar unless you find out what's going on, could you recreate a pull request? Hopefully these inconsistencies would disappear...

**Comment by arleyristar** [comment]
Yes, i know what is happening. Remember we i said that i had to revert some
things? That's it, it is comparing if a file i modified, but had to revert
back.

**Comment by arleyristar** [comment]
In this file specifically, I removed  stepsize and expansion because it
wan't needed anymore once it won't be using the variable length
representation.
About the spaces, that's easy, my vim automatically remove all the extra
spaces in lines that hasn't anything.

**Comment by arleyristar** [comment]
If you need me i'll be at the moses channel.
I know that the github review can be confusing when you are looking at a
reverted commit (because it isn't comparing the initial code, it's
comparing with the last commit that is ahead). I recommend you to compare
the final commit with the master of the project: "
https://github.com/opencog/moses/compare/master...arleyristar:origin/before_change_rep
"

**Comment by arleyristar** [comment]
I forgot to say, in the files changed tab.
When you look just at the beginning and the end is actually very small: 771
additions and 174 deletions in 11 files.
That's because:
1. I changed my own code a lot during the gsoc.
2. Because of the reverse that i had to do, so is less 660 additions and
1,744 deletions (yes a lot of deletions, the contin representation was
overcomplex).
3. In some commits there's test parts that i included, but i had to remove
to the final commit.

I could have reverted it, made a branch and than made a pull request to not
show the commits ahead, but the project could lose information. I wanted to
leave the hybrid and the contin representation change in the commits so
even if i don't finish these two and/or for whatever reason my fork is
removed, the project still have access to it.

**Comment by arleyristar** [comment]
*1,744 additions and 660 deletions

**Comment by linas** [comment]
When you make a comment on some code in a pull request, and a new commit
changes that code, then the comment "disappears" from github.  There's some
squirmy way to find it again, I don't recall.

**Comment by ngeiswei** [comment]
@arleyristar looks like you need to merge the master to your branch so I can merge (the merge button is grayed out). Thanks.

**Comment by ngeiswei** [comment]
@arleyristar Except for the fact that there is no unit test for ps, the PR looks good to me. Please merge the master so I can merge.

If you can add a ps test in MOSESUTest that would be ideal. Thanks.

**Comment by arleyristar** [comment]
Now that i've made a new pull resquest from master i'll close this one.

**Pull request closed without merging**
