### PR TITLE
Generate config-file package for moses

### PR DESCRIPTION
**Pull request by noskill**
This PR:
1) creates config-file cmake package, so that we can rid off of FindMoses.cmake in projects that use moses. 
2) deletes cmake files that are provided by cogutil

see issue https://github.com/opencog/cogutil/issues/113

### CODE REVIEW

**Comment by ngeiswei** [comment]
I didn't review at all but that looks cool. I suppose after that you could take care of https://github.com/opencog/as-moses.

**Comment by noskill** [comment]
@ngeiswei Ok, working on it..

**Comment by vsbogd** [comment]
Looks good for me.

**Comment by vsbogd** [comment]
@ngeiswei, I am ready to merge this PR for moses and https://github.com/opencog/opencog/pull/3263 if you don't see any blockers.

**Comment by ngeiswei** [comment]
I didn't look at blockers, so I don't see any ;-)

**Comment by vsbogd** [comment]
Thanks @noskill  !

**Pull request merged**
