### PR TITLE
Scheme program output

### PR DESCRIPTION
**Pull request by mahletA**

### CODE REVIEW

**Comment by linas** [comment]
I merged because it looked plausible, although I did not review this very carefully.  Some documentation, or an example, is needed.  For example, what does the actual scheme output look like?

**Comment by mahletA** [comment]
In the earlier version, moses output was only accessible either as a combo or a python output. Now,the scheme output is accessible and is in a from which can be directly loaded into the opencog atomspace.
example:- in a python shell
from opencog.pymoses import moses
moses = moses()
input_data = [[0,0,1],[0,1,0],[1,0,0],[1,1,1]]
output = moses.run (input=input_data ,scheme=True) 
output[0].program 
'''
 prints ' (AndLink (OrLink (NotLink (PredicateNode "$1")) (PredicateNode "$2")) (OrLink (PredicateNode "$1") (NotLink (PredicateNode "$2")))) '

'''
Also, it is possible to write programs with the best score in an output scheme file using the " write_scheme" function in case a separate file is needed for large input datasets ( but that is just an extra functionality)
Example-
moses.write_scheme(output)  # creates a file "moses_result.scm" with the best scoring programs

**Comment by linas** [comment]
thanks!

That documentation should go into either a README file in nthe moses repo, or onto a wiki page, or both.  I mean -- if you create something like this, its important for the world to know it exists, and know how to use it.

**Comment by ngeiswei** [comment]
@linas I've added this to MOSES a while back, I didn't really document it (except a line in the moses --help) cause it's very much experimental. But you're right it should.

**Pull request merged**
