### PR TITLE
Use OpenCogGccOptions.cmake

### PR DESCRIPTION
**Pull request by linas**
Remove boilerplate

### CODE REVIEW

**Comment by linas** [comment]
Won't build; there appear to be voluminous compiler warnings and outright failures. Is MOSES unmaintained?

**Comment by linas** [comment]
OK, root cause of failure seems to be that moses used `-std=gnu++0x` but this pull-req has `std=gnu++11`

**Comment by linas** [comment]
Although I am also getting these warnings:
```
-- Configuring done
CMake Warning (dev) in moses/feature-selection/CMakeLists.txt:
  Policy CMP0022 is not set: INTERFACE_LINK_LIBRARIES defines the link
  interface.  Run "cmake --help-policy CMP0022" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  Target "feature_selection" has an INTERFACE_LINK_LIBRARIES property which
  differs from its LINK_INTERFACE_LIBRARIES properties.

  INTERFACE_LINK_LIBRARIES:

    pthread;moses;/usr/local/lib/opencog/libcogutil.so;/usr/lib/x86_64-linux-gnu/libboost_program_options.so

  LINK_INTERFACE_LIBRARIES:

    moses;/usr/local/lib/opencog/libcogutil.so;/usr/lib/x86_64-linux-gnu/libboost_program_options.so

This warning is for project developers.  Use -Wno-dev to suppress it.
```

Again .. does anybody use moses any more, or is it now slowly decaying?

**Comment by ngeiswei** [comment]
MOSES is still maintained, although virtually no new features are being introduced as AS-MOSES is its successor. Let me look at this issue.

**Comment by linas** [comment]
Closing. This change was made in some other merge.

**Pull request closed without merging**
